[2023-05-23T08:54:00.572+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.Extract manual__2023-05-23T08:53:58.196081+00:00 [queued]>
[2023-05-23T08:54:00.591+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.Extract manual__2023-05-23T08:53:58.196081+00:00 [queued]>
[2023-05-23T08:54:00.591+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-23T08:54:00.616+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): Extract> on 2023-05-23 08:53:58.196081+00:00
[2023-05-23T08:54:00.624+0000] {standard_task_runner.py:57} INFO - Started process 1330 to run task
[2023-05-23T08:54:00.628+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Extract', 'manual__2023-05-23T08:53:58.196081+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp4pqhhooz']
[2023-05-23T08:54:00.631+0000] {standard_task_runner.py:85} INFO - Job 349: Subtask Extract
[2023-05-23T08:54:00.702+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.Extract manual__2023-05-23T08:53:58.196081+00:00 [running]> on host 41afa13826a4
[2023-05-23T08:54:00.869+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-23T08:53:58.196081+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-23T08:53:58.196081+00:00'
[2023-05-23T08:54:00.873+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-23T08:54:00.874+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python extract.py']
[2023-05-23T08:54:00.892+0000] {subprocess.py:86} INFO - Output:
[2023-05-23T08:54:01.013+0000] {subprocess.py:93} INFO - python: can't open file 'extract.py': [Errno 2] No such file or directory
[2023-05-23T08:54:01.017+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-05-23T08:54:01.034+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-05-23T08:54:01.041+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=Extract, execution_date=20230523T085358, start_date=20230523T085400, end_date=20230523T085401
[2023-05-23T08:54:01.061+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 349 for task Extract (Bash command failed. The command returned a non-zero exit code 2.; 1330)
[2023-05-23T08:54:01.081+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-23T08:54:01.131+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
