[2023-05-23T08:58:00.076+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.Transform manual__2023-05-23T08:57:48.764119+00:00 [queued]>
[2023-05-23T08:58:00.105+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.Transform manual__2023-05-23T08:57:48.764119+00:00 [queued]>
[2023-05-23T08:58:00.106+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-23T08:58:00.142+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): Transform> on 2023-05-23 08:57:48.764119+00:00
[2023-05-23T08:58:00.156+0000] {standard_task_runner.py:57} INFO - Started process 1420 to run task
[2023-05-23T08:58:00.163+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Transform', 'manual__2023-05-23T08:57:48.764119+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpz0e98ge2']
[2023-05-23T08:58:00.166+0000] {standard_task_runner.py:85} INFO - Job 351: Subtask Transform
[2023-05-23T08:58:00.261+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.Transform manual__2023-05-23T08:57:48.764119+00:00 [running]> on host 41afa13826a4
[2023-05-23T08:58:00.500+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2023-05-23T08:57:48.764119+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-23T08:57:48.764119+00:00'
[2023-05-23T08:58:00.505+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-23T08:58:00.507+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python transform.py']
[2023-05-23T08:58:00.532+0000] {subprocess.py:86} INFO - Output:
[2023-05-23T08:58:00.692+0000] {subprocess.py:93} INFO - python: can't open file 'transform.py': [Errno 2] No such file or directory
[2023-05-23T08:58:00.697+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-05-23T08:58:00.718+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-05-23T08:58:00.725+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=Transform, execution_date=20230523T085748, start_date=20230523T085800, end_date=20230523T085800
[2023-05-23T08:58:00.750+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 351 for task Transform (Bash command failed. The command returned a non-zero exit code 2.; 1420)
[2023-05-23T08:58:00.778+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-23T08:58:00.822+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
