[2023-05-25T08:10:57.872+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.copy_table manual__2023-05-25T08:10:49.528879+00:00 [queued]>
[2023-05-25T08:10:57.891+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.copy_table manual__2023-05-25T08:10:49.528879+00:00 [queued]>
[2023-05-25T08:10:57.892+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-25T08:10:57.916+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): copy_table> on 2023-05-25 08:10:49.528879+00:00
[2023-05-25T08:10:57.924+0000] {standard_task_runner.py:57} INFO - Started process 133 to run task
[2023-05-25T08:10:57.929+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'copy_table', 'manual__2023-05-25T08:10:49.528879+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmppbgqo8z9']
[2023-05-25T08:10:57.932+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask copy_table
[2023-05-25T08:10:57.996+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.copy_table manual__2023-05-25T08:10:49.528879+00:00 [running]> on host 6c149b085cf0
[2023-05-25T08:10:58.120+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='copy_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-25T08:10:49.528879+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-25T08:10:49.528879+00:00'
[2023-05-25T08:10:58.122+0000] {sql.py:262} INFO - Executing: COPY temp_table (firstname, lastname) FROM '/app/***/finalFile.csv' DELIMITER ',' CSV HEADER;
[2023-05-25T08:10:58.135+0000] {base.py:73} INFO - Using connection ID 'connectPostges' for task execution.
[2023-05-25T08:10:58.235+0000] {base.py:73} INFO - Using connection ID 'connectPostges' for task execution.
[2023-05-25T08:10:58.243+0000] {sql.py:375} INFO - Running statement: COPY temp_table (firstname, lastname) FROM '/app/***/finalFile.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2023-05-25T08:10:58.245+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "temp_table" does not exist

[2023-05-25T08:10:58.256+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=copy_table, execution_date=20230525T081049, start_date=20230525T081057, end_date=20230525T081058
[2023-05-25T08:10:58.273+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 51 for task copy_table (relation "temp_table" does not exist
; 133)
[2023-05-25T08:10:58.301+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-25T08:10:58.330+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
