[2023-05-23T08:48:21.260+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.Extract manual__2023-05-23T08:48:18.895605+00:00 [queued]>
[2023-05-23T08:48:21.276+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.Extract manual__2023-05-23T08:48:18.895605+00:00 [queued]>
[2023-05-23T08:48:21.276+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-23T08:48:21.303+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): Extract> on 2023-05-23 08:48:18.895605+00:00
[2023-05-23T08:48:21.312+0000] {standard_task_runner.py:57} INFO - Started process 1226 to run task
[2023-05-23T08:48:21.315+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Extract', 'manual__2023-05-23T08:48:18.895605+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpzknjou5y']
[2023-05-23T08:48:21.318+0000] {standard_task_runner.py:85} INFO - Job 346: Subtask Extract
[2023-05-23T08:48:21.384+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.Extract manual__2023-05-23T08:48:18.895605+00:00 [running]> on host 41afa13826a4
[2023-05-23T08:48:21.546+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-23T08:48:18.895605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-23T08:48:18.895605+00:00'
[2023-05-23T08:48:21.550+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-23T08:48:21.551+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python extract.py']
[2023-05-23T08:48:21.572+0000] {subprocess.py:86} INFO - Output:
[2023-05-23T08:48:21.752+0000] {subprocess.py:93} INFO - python: can't open file 'extract.py': [Errno 2] No such file or directory
[2023-05-23T08:48:21.757+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-05-23T08:48:21.782+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-05-23T08:48:21.791+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=Extract, execution_date=20230523T084818, start_date=20230523T084821, end_date=20230523T084821
[2023-05-23T08:48:21.815+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 346 for task Extract (Bash command failed. The command returned a non-zero exit code 2.; 1226)
[2023-05-23T08:48:21.850+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-23T08:48:21.896+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
