[2023-05-25T09:04:22.043+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.temp_table manual__2023-05-25T09:04:17.366207+00:00 [queued]>
[2023-05-25T09:04:22.064+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.temp_table manual__2023-05-25T09:04:17.366207+00:00 [queued]>
[2023-05-25T09:04:22.065+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-25T09:04:22.099+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): temp_table> on 2023-05-25 09:04:17.366207+00:00
[2023-05-25T09:04:22.109+0000] {standard_task_runner.py:57} INFO - Started process 92 to run task
[2023-05-25T09:04:22.113+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'temp_table', 'manual__2023-05-25T09:04:17.366207+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmprjf_k605']
[2023-05-25T09:04:22.116+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask temp_table
[2023-05-25T09:04:22.198+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.temp_table manual__2023-05-25T09:04:17.366207+00:00 [running]> on host 548872e0b964
[2023-05-25T09:04:22.390+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='temp_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-25T09:04:17.366207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-25T09:04:17.366207+00:00'
[2023-05-25T09:04:22.392+0000] {sql.py:262} INFO - Executing: 
            CREATE TABLE temp_table (
            firstname varchar(40),       
            lastname  varchar(40),
            age   integer,
            sex   varchar(15)
            )
        
[2023-05-25T09:04:22.408+0000] {base.py:73} INFO - Using connection ID 'connectPostges' for task execution.
[2023-05-25T09:04:22.564+0000] {base.py:73} INFO - Using connection ID 'connectPostges' for task execution.
[2023-05-25T09:04:22.607+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE temp_table (
            firstname varchar(40),       
            lastname  varchar(40),
            age   integer,
            sex   varchar(15)
            )
        , parameters: None
[2023-05-25T09:04:22.611+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "temp_table" already exists

[2023-05-25T09:04:22.626+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=temp_table, execution_date=20230525T090417, start_date=20230525T090422, end_date=20230525T090422
[2023-05-25T09:04:22.646+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 74 for task temp_table (relation "temp_table" already exists
; 92)
[2023-05-25T09:04:22.688+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-25T09:04:22.742+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
